name: docs

on:
  schedule:
    - cron: '30 06 * * *'
  push:
    branches: [master]
    paths:
      - 'packages/docs/**'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.6.2]
        pnpm-version: [8.15.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Get pnpm store directory
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ matrix.node-version }}-${{ matrix.pnpm-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ matrix.node-version }}-${{ matrix.pnpm-version }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build docs-dist
        run: pnpm run build:docs
      - name: Deploy to GitHub docs-dist
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: docs-dist
          folder: packages/docs/docs-dist

      - name: Deploy to dext7r docs-dist
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          FOLDER: packages/docs/docs-dist
          REPOSITORY_NAME: dext7r/dext7r
          GITHUB_TOKEN: ${{ secrets.VISUAL_DRAG_DEMO }}
          BRANCH: docs-dist
          CLEAN: true
          TARGET_FOLDER: ./

      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: dext7r.surge.sh
          project: ./packages/docs/docs-dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Upload surge service and generate preview URL
        id: deploy
        run: |
          export GITHUB_SHA=${{ github.sha }}
          export GITHUB_SHA_SUB=${GITHUB_SHA:0:7}
          export DEPLOY_DOMAIN=https://dext7r-$GITHUB_SHA_SUB.surge.sh
          npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.surge_token }}
          echo the preview URL is $DEPLOY_DOMAIN
          echo "::set-output name=url::$DEPLOY_DOMAIN"

  sync:
    runs-on: ubuntu-latest
    needs: pages
    steps:
      - name: Mirror the GitHub organization repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/dext7r
          dst: gitee/dext7r
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          timeout: '1h'
          debug: true
          force_update: true

  gitee:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Sync To Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:dext7r/dext7r.git
          destination-repo: git@gitee.com:dext7r/dext7r.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: h7ml@qq.com
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: dext7r/dext7r
          branch: docs-dist
