name: Update Dependencies

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.6.2]
        pnpm-version: [8.15.5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Get pnpm store directory
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-ncu-store-${{ matrix.node-version }}-${{ matrix.pnpm-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-ncu-store-${{ matrix.node-version }}-${{ matrix.pnpm-version }}-

      - name: Install dependencies
        run: |
          pnpm install
          npx envinfo --system --browsers --npmPackages -y
      - name: Update Dependencies
        run: pnpm ncu

      - name: Install updated dependencies
        run: |
          pnpm install --no-frozen-lockfile
          npx envinfo --npmPackages -y
      - name: Build and test
        id: build_and_test
        run: |
          pnpm build:gh-pages && pnpm run i18n
          echo "::set-output name=status::success"

      - name: Check for changes
        id: check_changes
        run: |
          if [ "${{ steps.build_and_test.outputs.status }}" == "success" ]; then
            echo "Changes detected and build successful. Proceeding with commit and push."
          else
            echo "Build failed or no changes detected. Exiting."
            exit 1
          fi

      - name: Commit changes
        if: steps.check_changes.outcome == 'success'
        run: |
          git config --global user.name 'actions-user'
          git config --global user.email 'shark@h7ml.cn'
          git add package.json pnpm-lock.yaml
          git commit -m "chore: Update dependencies" || exit 0

      - name: Push changes
        if: steps.check_changes.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_SECRET }}
