name: Update Dependencies

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21.6.2
          registry-url: https://registry.npmmirror.com

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates pnpm

      - name: Update Dependencies
        run: npx ncu -u --reject chalk,ora

      - name: Install updated dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build and test
        id: build_and_test
        run: |
          pnpm build:gh-pages && pnpm tp
          echo "::set-output name=status::success"

      - name: Check for changes
        id: check_changes
        run: |
          if [ "${{ steps.build_and_test.outputs.status }}" == "success" ]; then
            echo "Changes detected and build successful. Proceeding with commit and push."
          else
            echo "Build failed or no changes detected. Exiting."
            exit 1
          fi

      - name: Commit changes
        if: steps.check_changes.outcome == 'success'
        run: |
          git config --global user.name 'actions-user'
          git config --global user.email 'shark@h7ml.cn'
          git add package.json pnpm-lock.yaml
          git commit -m "chore: Update dependencies" || exit 0

      - name: Push changes
        if: steps.check_changes.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_SECRET }}
